### ISSUE TITLE
iconv-lite package

### ISSUE THREAD

**Issue by erictsai6** [biesbjerg/ngx-translate-po-http-loader#10]
Hey,

  First off thanks for your work on this po http loader.  We were using it before ultimately switching to the TranslateStaticLoader by converting our po files into json.  This issue is more to make you aware that packaging this with an application will also include iconv-lite which together results when gzipped results in an additional 150+kb 

![screen shot 2017-08-24 at 3 58 04 pm](https://user-images.githubusercontent.com/1450578/29685944-0c846c10-88e5-11e7-8584-b5ea1637ad3b.png)

**Comment by biesbjerg** [comment]
Thank you for the info. Unfortunately I don't see any way around it at this time, since it's a dependency of the `encoding` package, used by `gettext-parser` package.

Any suggestions?

**Comment by komachi** [comment]
I solved it with custom webpack loader.

po2json-loader.js
```
const gettext = require('gettext-parser');

module.exports = function(source) {
  this.cacheable();
  const domain = '';
  const po = gettext.po.parse(source, 'utf-8');
  if (!po.translations.hasOwnProperty(domain)) {
    return 'module.exports = {}';
  }
  const translations = Object.keys(po.translations[domain]).reduce((acc, key) => {
    const translation = po.translations[domain][key].msgstr.pop();
    if (key.length > 0 && translation.length > 0) {
      acc[key] = translation;
    }
    return acc;
  }, {});
  return `module.exports = ${JSON.stringify(translations)}`;
}
```

webpack config
```
rules: [
  {
     test: /\.po$/,
     use: [{
       loader: path.resolve('./po2json-loader')
      }]
    }
]
```

app.module.ts
```
export class WebpackTranslateLoader implements TranslateLoader {
  getTranslation(lang: string): Observable<{[key: string]: string}> {
    return from(import(`../assets/i18n/${lang}.po`));
  }
}

TranslateModule.forRoot({
  loader: {
    provide: TranslateLoader,
    useClass: WebpackTranslateLoader
  }
}),
```
You can use it the same way you use ngx-translate-po-http-loader, but without any client-side deps, reducing bundle size.

**Comment by daniel-bikemap** [comment]
@komachi This is a really elegant solution. Sadly, I can't get it to run - I always end up with an exception at this line:

```
return from(import(`./angular.po`));
The exception reads: error TS2307: Cannot find module './angular.po'.
```
Any advice?

**Comment by vtolstov** [comment]
any worked solution to minimize bundle size?
