### ISSUE TITLE
.map is not a function at TranslatePoHttpLoader.getTranslation 

### ISSUE THREAD

**Issue by ibagaric** [biesbjerg/ngx-translate-po-http-loader#16]
why do i get error that map operator is missing?
ERROR TypeError: this._http.get(...).map is not a function at TranslatePoHttpLoader.getTranslation (index.js:17)

![image](https://user-images.githubusercontent.com/12593739/33937766-065d3fde-e005-11e7-9ca8-634908c98a9e.png)

Also there is iconv-loader.js warning what was mentioned before 

Using Angular 5

**Comment by cvaliere** [comment]
fixed by my PR: https://github.com/biesbjerg/ngx-translate-po-http-loader/pull/14

@biesbjerg any chance you can merge it?

**Comment by biesbjerg** [comment]
New version published to NPM. 

Don't know what to do about the iconv-loader.js warning. It comes from the gettext dependency I'm using and is out of my hands, short of replacing the lib with something else.
