### ISSUE TITLE
Loading with SystemJS

### ISSUE THREAD

**Issue by reinhardholl** [biesbjerg/ngx-translate-po-http-loader#8]
Hi

I am trying to load this module using SystemJS but I am experiencing issues with loading dependencies. 

I have added the following to the SystemJS map:
`'@biesbjerg/ngx-translate-po-http-loader': 'node_modules/@biesbjerg/ngx-translate-po-http-loader/dist'`

Is there anything else that I need to do?

Thanks!

**Comment by biesbjerg** [comment]
Sorry. I don't have experience setting up SystemJS.
